// Offline recordings generated with the owner's saved HeyGen voice Fluff.
String proVoiceKey(String text) => text.trim().toLowerCase()
  .replaceAll(RegExp(r'\s+'), ' ').replaceAll(RegExp(r'[.!?…]+$'), '');

const proVoiceClips = <String, String>{
  'wie viele sterne siehst du': 'audio/pro/pro_001.mp3',
  'welche form ist das': 'audio/pro/pro_002.mp3',
  'was kommt als nächstes': 'audio/pro/pro_003.mp3',
  'du kannst wählen:': 'audio/pro/pro_004.mp3',
  '1': 'audio/pro/pro_005.mp3',
  'das ist 1 stern. du darfst jeden stern einzeln zählen': 'audio/pro/pro_006.mp3',
  '2': 'audio/pro/pro_007.mp3',
  'das sind 2 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_008.mp3',
  '3': 'audio/pro/pro_009.mp3',
  'das sind 3 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_010.mp3',
  '4': 'audio/pro/pro_011.mp3',
  'das sind 4 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_012.mp3',
  '5': 'audio/pro/pro_013.mp3',
  'das sind 5 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_014.mp3',
  '6': 'audio/pro/pro_015.mp3',
  'das sind 6 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_016.mp3',
  '7': 'audio/pro/pro_017.mp3',
  'das sind 7 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_018.mp3',
  '8': 'audio/pro/pro_019.mp3',
  'das sind 8 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_020.mp3',
  '9': 'audio/pro/pro_021.mp3',
  'das sind 9 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_022.mp3',
  'kreis': 'audio/pro/pro_023.mp3',
  'kreis – jede form sieht anders aus': 'audio/pro/pro_024.mp3',
  'dreieck': 'audio/pro/pro_025.mp3',
  'dreieck – jede form sieht anders aus': 'audio/pro/pro_026.mp3',
  'quadrat': 'audio/pro/pro_027.mp3',
  'quadrat – jede form sieht anders aus': 'audio/pro/pro_028.mp3',
  'stern': 'audio/pro/pro_029.mp3',
  'stern – jede form sieht anders aus': 'audio/pro/pro_030.mp3',
  'blauer kreis': 'audio/pro/pro_031.mp3',
  'das muster beginnt wieder mit blauer kreis': 'audio/pro/pro_032.mp3',
  'gelber kreis': 'audio/pro/pro_033.mp3',
  'das muster beginnt wieder mit gelber kreis': 'audio/pro/pro_034.mp3',
  'lila kreis': 'audio/pro/pro_035.mp3',
  'das muster beginnt wieder mit lila kreis': 'audio/pro/pro_036.mp3',
  'grüner kreis': 'audio/pro/pro_037.mp3',
  'das muster beginnt wieder mit grüner kreis': 'audio/pro/pro_038.mp3',
  'das muster beginnt wieder mit stern': 'audio/pro/pro_039.mp3',
  'herz': 'audio/pro/pro_040.mp3',
  'das muster beginnt wieder mit herz': 'audio/pro/pro_041.mp3',
  'blume': 'audio/pro/pro_042.mp3',
  'das muster beginnt wieder mit blume': 'audio/pro/pro_043.mp3',
  'baum': 'audio/pro/pro_044.mp3',
  'das muster beginnt wieder mit baum': 'audio/pro/pro_045.mp3',
  'teddybär': 'audio/pro/pro_046.mp3',
  'das muster beginnt wieder mit teddybär': 'audio/pro/pro_047.mp3',
  'buch': 'audio/pro/pro_048.mp3',
  'das muster beginnt wieder mit buch': 'audio/pro/pro_049.mp3',
  'mond': 'audio/pro/pro_050.mp3',
  'das muster beginnt wieder mit mond': 'audio/pro/pro_051.mp3',
  'sonne': 'audio/pro/pro_052.mp3',
  'das muster beginnt wieder mit sonne': 'audio/pro/pro_053.mp3',
  'regenbogen': 'audio/pro/pro_054.mp3',
  'das muster beginnt wieder mit regenbogen': 'audio/pro/pro_055.mp3',
  'dein turm fällt um. wie könntest du dich fühlen': 'audio/pro/pro_056.mp3',
  'traurig': 'audio/pro/pro_057.mp3',
  'hungrig': 'audio/pro/pro_058.mp3',
  'ausgeschlafen': 'audio/pro/pro_059.mp3',
  'du darfst traurig sein. wenn du magst, baust du später neu': 'audio/pro/pro_060.mp3',
  'jemand nimmt dir ungefragt dein spielzeug weg': 'audio/pro/pro_061.mp3',
  'wütend': 'audio/pro/pro_062.mp3',
  'müde': 'audio/pro/pro_063.mp3',
  'satt': 'audio/pro/pro_064.mp3',
  'wut ist okay. sag: ich möchte gefragt werden. du musst niemanden hauen': 'audio/pro/pro_065.mp3',
  'du hast lange gespielt und gähnst': 'audio/pro/pro_066.mp3',
  'erschrocken': 'audio/pro/pro_067.mp3',
  'dein körper braucht eine pause. ruhe ist wichtig': 'audio/pro/pro_068.mp3',
  'du schaffst etwas nach mehreren versuchen': 'audio/pro/pro_069.mp3',
  'stolz': 'audio/pro/pro_070.mp3',
  'durstig': 'audio/pro/pro_071.mp3',
  'du darfst stolz sein. du hast es in deinem tempo versucht': 'audio/pro/pro_072.mp3',
  'heute ist alles neu. du weißt noch nicht, was passiert': 'audio/pro/pro_073.mp3',
  'unsicher': 'audio/pro/pro_074.mp3',
  'unsicher sein ist okay. frag eine vertraute person, was als nächstes kommt': 'audio/pro/pro_075.mp3',
  'du freust dich auf ein spiel mit deinem freund': 'audio/pro/pro_076.mp3',
  'glücklich': 'audio/pro/pro_077.mp3',
  'freude darfst du zeigen. andere dürfen sich anders fühlen': 'audio/pro/pro_078.mp3',
  'dein freund ist traurig. was hilft': 'audio/pro/pro_079.mp3',
  'fragen: soll ich bei dir bleiben': 'audio/pro/pro_080.mp3',
  'sagen: stell dich nicht so an': 'audio/pro/pro_081.mp3',
  'sofort lachen': 'audio/pro/pro_082.mp3',
  'du kannst zuhören. dein freund entscheidet, ob er nähe möchte': 'audio/pro/pro_083.mp3',
  'du bist wütend. was kannst du tun': 'audio/pro/pro_084.mp3',
  'abstand nehmen und ruhig atmen': 'audio/pro/pro_085.mp3',
  'jemanden hauen': 'audio/pro/pro_086.mp3',
  'alles werfen': 'audio/pro/pro_087.mp3',
  'du darfst wütend sein. hände bleiben sicher. hol hilfe, wenn du sie brauchst': 'audio/pro/pro_088.mp3',
  'du möchtest mit einem spielzeug spielen, das jemand benutzt': 'audio/pro/pro_089.mp3',
  'freundlich fragen und warten': 'audio/pro/pro_090.mp3',
  'es einfach wegnehmen': 'audio/pro/pro_091.mp3',
  'schubsen': 'audio/pro/pro_092.mp3',
  'sag: darf ich danach dran sein? ein nein darfst du auch hören': 'audio/pro/pro_093.mp3',
  'du schaffst den reißverschluss noch nicht': 'audio/pro/pro_094.mp3',
  'um hilfe bitten': 'audio/pro/pro_095.mp3',
  'dich selbst schimpfen': 'audio/pro/pro_096.mp3',
  'die jacke wegwerfen': 'audio/pro/pro_097.mp3',
  'sag: kannst du mir bitte helfen? hilfe holen ist mutig': 'audio/pro/pro_098.mp3',
  'du hast aus versehen wasser verschüttet': 'audio/pro/pro_099.mp3',
  'bescheid sagen und zusammen aufwischen': 'audio/pro/pro_100.mp3',
  'jemand anderem die schuld geben': 'audio/pro/pro_101.mp3',
  'so tun, als wäre nichts': 'audio/pro/pro_102.mp3',
  'fehler passieren. ein erwachsener kann dir beim aufwischen helfen': 'audio/pro/pro_103.mp3',
  'du möchtest gerade keine umarmung': 'audio/pro/pro_104.mp3',
  'nein sagen. mein körper gehört mir': 'audio/pro/pro_105.mp3',
  'du musst immer ja sagen': 'audio/pro/pro_106.mp3',
  'du darfst nie etwas sagen': 'audio/pro/pro_107.mp3',
  'dein nein zählt. nähe soll sich für dich gut anfühlen': 'audio/pro/pro_108.mp3',
  'dein freund möchte nicht teilen': 'audio/pro/pro_109.mp3',
  'nach einer gemeinsamen lösung fragen': 'audio/pro/pro_110.mp3',
  'es ihm wegnehmen': 'audio/pro/pro_111.mp3',
  'ihn auslachen': 'audio/pro/pro_112.mp3',
  'teilen darf freiwillig sein. vielleicht könnt ihr abwechseln oder anders spielen': 'audio/pro/pro_113.mp3',
  'du hast jemanden aus versehen verletzt': 'audio/pro/pro_114.mp3',
  'entschuldigen und fragen, was hilft': 'audio/pro/pro_115.mp3',
  'darüber lachen': 'audio/pro/pro_116.mp3',
  'einfach weitergehen': 'audio/pro/pro_117.mp3',
  'sag: das tut mir leid. brauchst du hilfe? hol einen erwachsenen dazu': 'audio/pro/pro_118.mp3',
  'du willst über eine straße gehen': 'audio/pro/pro_119.mp3',
  'mit einer erwachsenen person gehen': 'audio/pro/pro_120.mp3',
  'einfach loslaufen': 'audio/pro/pro_121.mp3',
  'nur dem ball folgen': 'audio/pro/pro_122.mp3',
  'an der straße hältst du an. geh mit einer vertrauten erwachsenen person': 'audio/pro/pro_123.mp3',
  'dir ist etwas unheimlich': 'audio/pro/pro_124.mp3',
  'zu einer vertrauten person gehen': 'audio/pro/pro_125.mp3',
  'du musst alles allein schaffen': 'audio/pro/pro_126.mp3',
  'nichts erzählen': 'audio/pro/pro_127.mp3',
  'du darfst hilfe holen und erzählen, was dir angst macht': 'audio/pro/pro_128.mp3',
  'finde zwei gleiche bilder': 'audio/pro/pro_129.mp3',
  'ein paar gefunden': 'audio/pro/pro_130.mp3',
  'schau dir die bilder an. du darfst es neu versuchen': 'audio/pro/pro_131.mp3',
  'schau noch einmal hin. du darfst dir zeit nehmen': 'audio/pro/pro_132.mp3',
  'du hast alle paare gefunden. dein entdecker-sticker ist in deinem album': 'audio/pro/pro_133.mp3',
  'du hast etwas neues entdeckt. dein entdecker-sticker ist in deinem album': 'audio/pro/pro_134.mp3',
  'dein fortschritt konnte nicht gespeichert werden. du kannst es noch einmal versuchen': 'audio/pro/pro_135.mp3',
  'willkommen in meinem malatelier! hier kannst du malen, ein ausmalbild aussuchen und deine bilder im album anschauen': 'audio/pro/pro_136.mp3',
  'freies malen': 'audio/pro/pro_137.mp3',
  'such dir eine farbe aus. male in deinem tempo. wenn du fertig bist, kannst du dein bild im album speichern': 'audio/pro/pro_138.mp3',
  'dein bild ist im album gespeichert': 'audio/pro/pro_139.mp3',
  'dein bild konnte nicht gespeichert werden. bitte versuche es noch einmal': 'audio/pro/pro_140.mp3',
  'rosa': 'audio/pro/pro_141.mp3',
  'gelb': 'audio/pro/pro_142.mp3',
  'grün': 'audio/pro/pro_143.mp3',
  'blau': 'audio/pro/pro_144.mp3',
  'lila': 'audio/pro/pro_145.mp3',
  'rot': 'audio/pro/pro_146.mp3',
  'braun': 'audio/pro/pro_147.mp3',
  'schwarz': 'audio/pro/pro_148.mp3',
  'weiß': 'audio/pro/pro_149.mp3',
  'fluff baut einen turm': 'audio/pro/pro_150.mp3',
  'fluffs blumengarten': 'audio/pro/pro_151.mp3',
  'fluff und die sterne': 'audio/pro/pro_152.mp3',
  'fluffs lesezeit': 'audio/pro/pro_153.mp3',
  'fluff hilft einem freund': 'audio/pro/pro_154.mp3',
  'gute nacht, fluff': 'audio/pro/pro_155.mp3',
  'formen entdecken': 'audio/pro/pro_156.mp3',
  'meine zählsterne': 'audio/pro/pro_157.mp3',
  'der weg zu fluff': 'audio/pro/pro_158.mp3',
  'muster weiterzeichnen': 'audio/pro/pro_159.mp3',
  'mein gefühl heute': 'audio/pro/pro_160.mp3',
  'mein eigenes sternenglas': 'audio/pro/pro_161.mp3',
};
