// Offline recordings generated with the owner's saved HeyGen voice Fluff.
String proVoiceKey(String text) => text.trim().toLowerCase()
  .replaceAll(RegExp(r'\s+'), ' ').replaceAll(RegExp(r'[.!?…]+$'), '');

const proVoiceClips = <String, String>{
  'wie viele sterne siehst du': 'audio/pro/pro_001.mp3',
  'welche form ist das': 'audio/pro/pro_002.mp3',
  'was kommt als nächstes': 'audio/pro/pro_003.mp3',
  'du kannst wählen:': 'audio/pro/pro_004.mp3',
  '1': 'audio/pro/pro_005.mp3',
  'das ist 1 stern. du darfst jeden stern einzeln zählen': 'audio/pro/pro_006.mp3',
  '2': 'audio/pro/pro_007.mp3',
  'das sind 2 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_008.mp3',
  '3': 'audio/pro/pro_009.mp3',
  'das sind 3 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_010.mp3',
  '4': 'audio/pro/pro_011.mp3',
  'das sind 4 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_012.mp3',
  '5': 'audio/pro/pro_013.mp3',
  'das sind 5 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_014.mp3',
  '6': 'audio/pro/pro_015.mp3',
  'das sind 6 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_016.mp3',
  '7': 'audio/pro/pro_017.mp3',
  'das sind 7 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_018.mp3',
  '8': 'audio/pro/pro_019.mp3',
  'das sind 8 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_020.mp3',
  '9': 'audio/pro/pro_021.mp3',
  'das sind 9 sterne. du darfst jeden stern einzeln zählen': 'audio/pro/pro_022.mp3',
  'kreis': 'audio/pro/pro_023.mp3',
  'kreis – jede form sieht anders aus': 'audio/pro/pro_024.mp3',
  'dreieck': 'audio/pro/pro_025.mp3',
  'dreieck – jede form sieht anders aus': 'audio/pro/pro_026.mp3',
  'quadrat': 'audio/pro/pro_027.mp3',
  'quadrat – jede form sieht anders aus': 'audio/pro/pro_028.mp3',
  'stern': 'audio/pro/pro_029.mp3',
  'stern – jede form sieht anders aus': 'audio/pro/pro_030.mp3',
  'blauer kreis': 'audio/pro/pro_031.mp3',
  'das muster beginnt wieder mit blauer kreis': 'audio/pro/pro_032.mp3',
  'gelber kreis': 'audio/pro/pro_033.mp3',
  'das muster beginnt wieder mit gelber kreis': 'audio/pro/pro_034.mp3',
  'lila kreis': 'audio/pro/pro_035.mp3',
  'das muster beginnt wieder mit lila kreis': 'audio/pro/pro_036.mp3',
  'grüner kreis': 'audio/pro/pro_037.mp3',
  'das muster beginnt wieder mit grüner kreis': 'audio/pro/pro_038.mp3',
  'das muster beginnt wieder mit stern': 'audio/pro/pro_039.mp3',
  'herz': 'audio/pro/pro_040.mp3',
  'das muster beginnt wieder mit herz': 'audio/pro/pro_041.mp3',
  'blume': 'audio/pro/pro_042.mp3',
  'das muster beginnt wieder mit blume': 'audio/pro/pro_043.mp3',
  'baum': 'audio/pro/pro_044.mp3',
  'das muster beginnt wieder mit baum': 'audio/pro/pro_045.mp3',
  'teddybär': 'audio/pro/pro_046.mp3',
  'das muster beginnt wieder mit teddybär': 'audio/pro/pro_047.mp3',
  'buch': 'audio/pro/pro_048.mp3',
  'das muster beginnt wieder mit buch': 'audio/pro/pro_049.mp3',
  'mond': 'audio/pro/pro_050.mp3',
  'das muster beginnt wieder mit mond': 'audio/pro/pro_051.mp3',
  'sonne': 'audio/pro/pro_052.mp3',
  'das muster beginnt wieder mit sonne': 'audio/pro/pro_053.mp3',
  'regenbogen': 'audio/pro/pro_054.mp3',
  'das muster beginnt wieder mit regenbogen': 'audio/pro/pro_055.mp3',
  'dein turm fällt um. wie könntest du dich fühlen': 'audio/pro/pro_056.mp3',
  'traurig': 'audio/pro/pro_057.mp3',
  'hungrig': 'audio/pro/pro_058.mp3',
  'ausgeschlafen': 'audio/pro/pro_059.mp3',
  'du darfst traurig sein. wenn du magst, baust du später neu': 'audio/pro/pro_060.mp3',
  'jemand nimmt dir ungefragt dein spielzeug weg': 'audio/pro/pro_061.mp3',
  'wütend': 'audio/pro/pro_062.mp3',
  'müde': 'audio/pro/pro_063.mp3',
  'satt': 'audio/pro/pro_064.mp3',
  'wut ist okay. sag: ich möchte gefragt werden. du musst niemanden hauen': 'audio/pro/pro_065.mp3',
  'du hast lange gespielt und gähnst': 'audio/pro/pro_066.mp3',
  'erschrocken': 'audio/pro/pro_067.mp3',
  'dein körper braucht eine pause. ruhe ist wichtig': 'audio/pro/pro_068.mp3',
  'du schaffst etwas nach mehreren versuchen': 'audio/pro/pro_069.mp3',
  'stolz': 'audio/pro/pro_070.mp3',
  'durstig': 'audio/pro/pro_071.mp3',
  'du darfst stolz sein. du hast es in deinem tempo versucht': 'audio/pro/pro_072.mp3',
  'heute ist alles neu. du weißt noch nicht, was passiert': 'audio/pro/pro_073.mp3',
  'unsicher': 'audio/pro/pro_074.mp3',
  'unsicher sein ist okay. frag eine vertraute person, was als nächstes kommt': 'audio/pro/pro_075.mp3',
  'du freust dich auf ein spiel mit deinem freund': 'audio/pro/pro_076.mp3',
  'glücklich': 'audio/pro/pro_077.mp3',
  'freude darfst du zeigen. andere dürfen sich anders fühlen': 'audio/pro/pro_078.mp3',
  'dein freund ist traurig. was hilft': 'audio/pro/pro_079.mp3',
  'fragen: soll ich bei dir bleiben': 'audio/pro/pro_080.mp3',
  'sagen: stell dich nicht so an': 'audio/pro/pro_081.mp3',
  'sofort lachen': 'audio/pro/pro_082.mp3',
  'du kannst zuhören. dein freund entscheidet, ob er nähe möchte': 'audio/pro/pro_083.mp3',
  'du bist wütend. was kannst du tun': 'audio/pro/pro_084.mp3',
  'abstand nehmen und ruhig atmen': 'audio/pro/pro_085.mp3',
  'jemanden hauen': 'audio/pro/pro_086.mp3',
  'alles werfen': 'audio/pro/pro_087.mp3',
  'du darfst wütend sein. hände bleiben sicher. hol hilfe, wenn du sie brauchst': 'audio/pro/pro_088.mp3',
  'du möchtest mit einem spielzeug spielen, das jemand benutzt': 'audio/pro/pro_089.mp3',
  'freundlich fragen und warten': 'audio/pro/pro_090.mp3',
  'es einfach wegnehmen': 'audio/pro/pro_091.mp3',
  'schubsen': 'audio/pro/pro_092.mp3',
  'sag: darf ich danach dran sein? ein nein darfst du auch hören': 'audio/pro/pro_093.mp3',
  'du schaffst den reißverschluss noch nicht': 'audio/pro/pro_094.mp3',
  'um hilfe bitten': 'audio/pro/pro_095.mp3',
  'dich selbst schimpfen': 'audio/pro/pro_096.mp3',
  'die jacke wegwerfen': 'audio/pro/pro_097.mp3',
  'sag: kannst du mir bitte helfen? hilfe holen ist mutig': 'audio/pro/pro_098.mp3',
  'du hast aus versehen wasser verschüttet': 'audio/pro/pro_099.mp3',
  'bescheid sagen und zusammen aufwischen': 'audio/pro/pro_100.mp3',
  'jemand anderem die schuld geben': 'audio/pro/pro_101.mp3',
  'so tun, als wäre nichts': 'audio/pro/pro_102.mp3',
  'fehler passieren. ein erwachsener kann dir beim aufwischen helfen': 'audio/pro/pro_103.mp3',
  'du möchtest gerade keine umarmung': 'audio/pro/pro_104.mp3',
  'nein sagen. mein körper gehört mir': 'audio/pro/pro_105.mp3',
  'du musst immer ja sagen': 'audio/pro/pro_106.mp3',
  'du darfst nie etwas sagen': 'audio/pro/pro_107.mp3',
  'dein nein zählt. nähe soll sich für dich gut anfühlen': 'audio/pro/pro_108.mp3',
  'dein freund möchte nicht teilen': 'audio/pro/pro_109.mp3',
  'nach einer gemeinsamen lösung fragen': 'audio/pro/pro_110.mp3',
  'es ihm wegnehmen': 'audio/pro/pro_111.mp3',
  'ihn auslachen': 'audio/pro/pro_112.mp3',
  'teilen darf freiwillig sein. vielleicht könnt ihr abwechseln oder anders spielen': 'audio/pro/pro_113.mp3',
  'du hast jemanden aus versehen verletzt': 'audio/pro/pro_114.mp3',
  'entschuldigen und fragen, was hilft': 'audio/pro/pro_115.mp3',
  'darüber lachen': 'audio/pro/pro_116.mp3',
  'einfach weitergehen': 'audio/pro/pro_117.mp3',
  'sag: das tut mir leid. brauchst du hilfe? hol einen erwachsenen dazu': 'audio/pro/pro_118.mp3',
  'du willst über eine straße gehen': 'audio/pro/pro_119.mp3',
  'mit einer erwachsenen person gehen': 'audio/pro/pro_120.mp3',
  'einfach loslaufen': 'audio/pro/pro_121.mp3',
  'nur dem ball folgen': 'audio/pro/pro_122.mp3',
  'an der straße hältst du an. geh mit einer vertrauten erwachsenen person': 'audio/pro/pro_123.mp3',
  'dir ist etwas unheimlich': 'audio/pro/pro_124.mp3',
  'zu einer vertrauten person gehen': 'audio/pro/pro_125.mp3',
  'du musst alles allein schaffen': 'audio/pro/pro_126.mp3',
  'nichts erzählen': 'audio/pro/pro_127.mp3',
  'du darfst hilfe holen und erzählen, was dir angst macht': 'audio/pro/pro_128.mp3',
  'finde zwei gleiche bilder': 'audio/pro/pro_129.mp3',
  'ein paar gefunden': 'audio/pro/pro_130.mp3',
  'schau dir die bilder an. du darfst es neu versuchen': 'audio/pro/pro_131.mp3',
  'schau noch einmal hin. du darfst dir zeit nehmen': 'audio/pro/pro_132.mp3',
  'du hast alle paare gefunden. dein entdecker-sticker ist in deinem album': 'audio/pro/pro_133.mp3',
  'du hast etwas neues entdeckt. dein entdecker-sticker ist in deinem album': 'audio/pro/pro_134.mp3',
  'dein fortschritt konnte nicht gespeichert werden. du kannst es noch einmal versuchen': 'audio/pro/pro_135.mp3',
  'willkommen in meinem malatelier! hier kannst du malen, ein ausmalbild aussuchen und deine bilder im album anschauen': 'audio/pro/pro_136.mp3',
  'freies malen': 'audio/pro/pro_137.mp3',
  'such dir eine farbe aus. male in deinem tempo. wenn du fertig bist, kannst du dein bild im album speichern': 'audio/pro/pro_138.mp3',
  'dein bild ist im album gespeichert': 'audio/pro/pro_139.mp3',
  'dein bild konnte nicht gespeichert werden. bitte versuche es noch einmal': 'audio/pro/pro_140.mp3',
  'rosa': 'audio/pro/pro_141.mp3',
  'gelb': 'audio/pro/pro_142.mp3',
  'grün': 'audio/pro/pro_143.mp3',
  'blau': 'audio/pro/pro_144.mp3',
  'lila': 'audio/pro/pro_145.mp3',
  'rot': 'audio/pro/pro_146.mp3',
  'braun': 'audio/pro/pro_147.mp3',
  'schwarz': 'audio/pro/pro_148.mp3',
  'weiß': 'audio/pro/pro_149.mp3',
  'fluff baut einen turm': 'audio/pro/pro_150.mp3',
  'fluffs blumengarten': 'audio/pro/pro_151.mp3',
  'fluff und die sterne': 'audio/pro/pro_152.mp3',
  'fluffs lesezeit': 'audio/pro/pro_153.mp3',
  'fluff hilft einem freund': 'audio/pro/pro_154.mp3',
  'gute nacht, fluff': 'audio/pro/pro_155.mp3',
  'formen entdecken': 'audio/pro/pro_156.mp3',
  'meine zählsterne': 'audio/pro/pro_157.mp3',
  'der weg zu fluff': 'audio/pro/pro_158.mp3',
  'muster weiterzeichnen': 'audio/pro/pro_159.mp3',
  'mein gefühl heute': 'audio/pro/pro_160.mp3',
  'mein eigenes sternenglas': 'audio/pro/pro_161.mp3',
  'ich bin fluff. wir merken uns bilder und finden zwei gleiche. du entscheidest, wann die karten wieder zugedeckt werden': 'audio/pro/pro_162.mp3',
  'ich bin fluff. wir zählen jeden stern einmal. die letzte zahl sagt uns, wie viele sterne es zusammen sind': 'audio/pro/pro_163.mp3',
  'ich bin fluff. wir untersuchen formen. wir entdecken ecken, runde linien und die spitzen eines sterns': 'audio/pro/pro_164.mp3',
  'ich bin fluff. wir entdecken eine gruppe, die sich wiederholt. dann setzen wir das muster fort': 'audio/pro/pro_165.mp3',
  'ich bin fluff. wir lernen wörter für gefühle. menschen dürfen sich verschieden fühlen. dann probieren wir aus, was helfen kann': 'audio/pro/pro_166.mp3',
  'ich bin fluff. wir üben freundliche worte, hilfe holen und nein sagen. wir spielen kleine alltagssituationen zusammen durch': 'audio/pro/pro_167.mp3',
  'du hast dir bilder und ihre plätze gemerkt und gleiche bilder verglichen': 'audio/pro/pro_168.mp3',
  'du hast jeden stern einmal gezählt. die letzte zahl nennt die ganze menge': 'audio/pro/pro_169.mp3',
  'du hast formen an ihren ecken, runden linien und spitzen erkannt': 'audio/pro/pro_170.mp3',
  'du hast wiederkehrende gruppen entdeckt und muster fortgesetzt': 'audio/pro/pro_171.mp3',
  'du hast gefühle benannt und ausprobiert, was dir helfen könnte. alle gefühle dürfen da sein': 'audio/pro/pro_172.mp3',
  'du hast freundliche worte, grenzen und hilfe holen geübt. du darfst dir unterstützung holen': 'audio/pro/pro_173.mp3',
  'schau auf das bild und merke dir seinen platz. suche dann dasselbe bild auf einer anderen karte. ich kann dir ein paar zeigen': 'audio/pro/pro_174.mp3',
  'tippe jeden stern genau einmal an. zähle mit mir mit. die letzte zahl sagt, wie viele es zusammen sind': 'audio/pro/pro_175.mp3',
  'fahre die form mit deinem finger nach. tippe die markierten stellen an. wir untersuchen sie zusammen': 'audio/pro/pro_176.mp3',
  'schau auf die erste farbig umrahmte gruppe. tippe ihre bilder der reihe nach an. dieselbe gruppe kommt wieder': 'audio/pro/pro_177.mp3',
  'es gibt hier kein falsches gefühl. überlege, wie es dir in dieser geschichte gehen könnte. du darfst auch noch unsicher sein': 'audio/pro/pro_178.mp3',
  'überlege: bleiben alle sicher? darf jeder nein sagen? welche worte helfen, ohne jemandem weh zu tun': 'audio/pro/pro_179.mp3',
  'tippe die sterne an und zähle mit mir': 'audio/pro/pro_180.mp3',
  'alle sterne sind gezählt. welche zahl war die letzte': 'audio/pro/pro_181.mp3',
  'vergleiche deine zahl mit der letzten zählzahl. du kannst die sterne noch einmal zählen': 'audio/pro/pro_182.mp3',
  'die letzte zählzahl sagt uns, wie viele sterne es zusammen sind': 'audio/pro/pro_183.mp3',
  'tippe auf die runde linie. findest du eine ecke': 'audio/pro/pro_184.mp3',
  'tippe die drei markierten ecken an': 'audio/pro/pro_185.mp3',
  'tippe die vier markierten ecken an': 'audio/pro/pro_186.mp3',
  'tippe die fünf äußeren spitzen an': 'audio/pro/pro_187.mp3',
  'ein kreis ist rund und hat keine ecken': 'audio/pro/pro_188.mp3',
  'ein dreieck hat drei ecken und drei seiten': 'audio/pro/pro_189.mp3',
  'ein quadrat hat vier ecken. seine vier seiten sind gleich lang': 'audio/pro/pro_190.mp3',
  'dieser stern hat fünf äußere spitzen. dazwischen liegen die inneren ecken': 'audio/pro/pro_191.mp3',
  'du hast die form untersucht. wie heißt sie': 'audio/pro/pro_192.mp3',
  'schau auf die eigenschaften der form. ich zeige sie dir noch einmal': 'audio/pro/pro_193.mp3',
  'tippe die erste gruppe von links nach rechts an. was wiederholt sich': 'audio/pro/pro_194.mp3',
  'schau auf das letzte bild. welches bild folgt in der wiederkehrenden gruppe': 'audio/pro/pro_195.mp3',
  'gehe die gruppe noch einmal durch. sie beginnt nach ihrem letzten bild wieder von vorn': 'audio/pro/pro_196.mp3',
  'diese gruppe wiederholt sich immer wieder': 'audio/pro/pro_197.mp3',
  'finde zwei gleiche bilder. merke dir auch, wo sie liegen': 'audio/pro/pro_198.mp3',
  'merke dir das bild und seinen platz. suche jetzt das gleiche bild': 'audio/pro/pro_199.mp3',
  'die beiden bilder sind gleich. du hast ein paar gefunden': 'audio/pro/pro_200.mp3',
  'diese bilder sind verschieden. schau auf ihre plätze. wenn du bereit bist, deckst du sie zu und suchst weiter': 'audio/pro/pro_201.mp3',
  'hier liegen zwei gleiche bilder. merke dir ihre plätze. decke sie zu und suche das paar selbst': 'audio/pro/pro_202.mp3',
  'schau dir die bilder und ihre plätze an. wenn du bereit bist, deckst du sie zu und suchst selbst': 'audio/pro/pro_203.mp3',
  'du hast alle paare gefunden. möchtest du deinen sticker sammeln': 'audio/pro/pro_204.mp3',
  'spielsachen': 'audio/pro/pro_205.mp3',
  'zahnbürste': 'audio/pro/pro_206.mp3',
  'tasche': 'audio/pro/pro_207.mp3',
  'wie könntest du dich in dieser geschichte fühlen': 'audio/pro/pro_208.mp3',
  'menschen können in derselben situation verschieden fühlen. dein gefühl darf da sein': 'audio/pro/pro_209.mp3',
  'was möchtest du jetzt mit mir ausprobieren': 'audio/pro/pro_210.mp3',
  'traurig. vielleicht brauchst du trost oder zeit. du darfst hilfe holen': 'audio/pro/pro_211.mp3',
  'wütend. wut darf da sein. wir halten unsere hände sicher und holen hilfe, wenn wir sie brauchen': 'audio/pro/pro_212.mp3',
  'müde. dein körper darf sich ausruhen. eine pause kann helfen': 'audio/pro/pro_213.mp3',
  'stolz. du darfst dich über deinen versuch freuen und davon erzählen': 'audio/pro/pro_214.mp3',
  'unsicher. du musst noch nicht alles wissen. eine vertraute person kann dir helfen': 'audio/pro/pro_215.mp3',
  'glücklich. du darfst deine freude zeigen. andere dürfen sich anders fühlen': 'audio/pro/pro_216.mp3',
  'du musst dein gefühl noch nicht kennen. du darfst dir zeit nehmen oder mit jemandem darüber sprechen': 'audio/pro/pro_217.mp3',
  'langsam atmen': 'audio/pro/pro_218.mp3',
  'mit jemandem sprechen': 'audio/pro/pro_219.mp3',
  'eine pause machen': 'audio/pro/pro_220.mp3',
  'wir atmen dreimal ruhig zusammen. tippe im tempo deines atems. halte die luft nicht an': 'audio/pro/pro_221.mp3',
  'atme ruhig ein': 'audio/pro/pro_222.mp3',
  'atme langsam aus': 'audio/pro/pro_223.mp3',
  'wir haben ruhig geatmet. schau, wie es dir jetzt geht. du darfst dir weitere hilfe holen': 'audio/pro/pro_224.mp3',
  'wähle einen satz. hör ihn dir an und probiere, ihn selbst zu sagen. du brauchst dafür kein mikrofon': 'audio/pro/pro_225.mp3',
  'ich möchte dir erzählen, wie ich mich fühle': 'audio/pro/pro_226.mp3',
  'kannst du bitte bei mir bleiben': 'audio/pro/pro_227.mp3',
  'ich brauche gerade hilfe': 'audio/pro/pro_228.mp3',
  'du hast einen satz zum hilfe holen geübt. eine vertraute person kann dir zuhören': 'audio/pro/pro_229.mp3',
  'mach es dir bequem. du darfst eine ruhige pause machen. tippe erst weiter, wenn du bereit bist': 'audio/pro/pro_230.mp3',
  'du hast dir zeit für eine pause genommen. du darfst immer wieder eine pause machen': 'audio/pro/pro_231.mp3',
  'jetzt üben wir einen satz für diese situation. hör zu und probiere, ihn selbst zu sagen': 'audio/pro/pro_232.mp3',
  'überlege noch einmal. freundliche worte und sichere hände helfen. ein nein zählt': 'audio/pro/pro_233.mp3',
  'du darfst den satz laut oder leise üben. wenn du bereit bist, spielen wir weiter': 'audio/pro/pro_234.mp3',
  'dein entdecker-sticker ist in deinem album. du kannst jederzeit weiter üben': 'audio/pro/pro_235.mp3',
  'weiß ich noch nicht': 'audio/pro/pro_236.mp3',
  'dein turm fällt um': 'audio/pro/pro_237.mp3',
  'darf ich danach dran sein': 'audio/pro/pro_238.mp3',
  'dein freund sagt: ich spiele noch. was machst du': 'audio/pro/pro_239.mp3',
  'du hast gefragt und das nein respektiert. ihr könnt später wieder fragen': 'audio/pro/pro_240.mp3',
  'warten oder etwas anderes spielen': 'audio/pro/pro_241.mp3',
  'das spielzeug doch wegnehmen': 'audio/pro/pro_242.mp3',
  'kannst du mir bitte helfen': 'audio/pro/pro_243.mp3',
  'eine vertraute person hilft dir beim anfang. was kannst du tun': 'audio/pro/pro_244.mp3',
  'hilfe annehmen und weiter probieren gehören zum lernen': 'audio/pro/pro_245.mp3',
  'danke sagen und den rest gemeinsam probieren': 'audio/pro/pro_246.mp3',
  'dich schimpfen, weil du hilfe gebraucht hast': 'audio/pro/pro_247.mp3',
  'ich habe wasser verschüttet. kannst du mir beim aufwischen helfen': 'audio/pro/pro_248.mp3',
  'eine erwachsene person bringt ein tuch. was machst du': 'audio/pro/pro_249.mp3',
  'du hast bescheid gesagt und hilfe angenommen. fehler dürfen passieren': 'audio/pro/pro_250.mp3',
  'mit ihrer hilfe aufwischen': 'audio/pro/pro_251.mp3',
  'weglaufen und niemandem etwas sagen': 'audio/pro/pro_252.mp3',
  'nein, das möchte ich gerade nicht': 'audio/pro/pro_253.mp3',
  'die andere person möchte dich trotzdem umarmen. was hilft': 'audio/pro/pro_254.mp3',
  'deine grenze zählt. eine vertraute person kann dich unterstützen': 'audio/pro/pro_255.mp3',
  'bei meinem nein bleiben und unterstützung holen': 'audio/pro/pro_256.mp3',
  'ja sagen, obwohl es sich nicht gut anfühlt': 'audio/pro/pro_257.mp3',
  'möchtest du später mit mir abwechseln': 'audio/pro/pro_258.mp3',
  'dein freund sagt: jetzt noch nicht. was machst du': 'audio/pro/pro_259.mp3',
  'teilen ist freiwillig. ihr dürft gemeinsam nach einer anderen idee suchen': 'audio/pro/pro_260.mp3',
  'sein nein achten und etwas anderes spielen': 'audio/pro/pro_261.mp3',
  'ihn zum teilen zwingen': 'audio/pro/pro_262.mp3',
  'das tut mir leid. brauchst du hilfe': 'audio/pro/pro_263.mp3',
  'das andere kind hat schmerzen. was machst du jetzt': 'audio/pro/pro_264.mp3',
  'bei schmerzen holst du eine erwachsene person. sie kann sich kümmern': 'audio/pro/pro_265.mp3',
  'eine erwachsene person dazu holen': 'audio/pro/pro_266.mp3',
  'weiter spielen, ohne etwas zu sagen': 'audio/pro/pro_267.mp3',
  'ich warte auf eine erwachsene person': 'audio/pro/pro_268.mp3',
  'dein ball rollt auf die straße. was machst du': 'audio/pro/pro_269.mp3',
  'du bleibst sicher stehen. eine erwachsene person kümmert sich um den ball': 'audio/pro/pro_270.mp3',
  'anhalten und einer erwachsenen person bescheid sagen': 'audio/pro/pro_271.mp3',
  'schnell hinterher rennen': 'audio/pro/pro_272.mp3',
  'mir ist unheimlich. bitte bleib bei mir': 'audio/pro/pro_273.mp3',
  'eine vertraute person fragt: was brauchst du': 'audio/pro/pro_274.mp3',
  'du darfst sagen, was du brauchst. hilfe holen ist erlaubt': 'audio/pro/pro_275.mp3',
  'erzählen und sagen, welche hilfe ich möchte': 'audio/pro/pro_276.mp3',
  'so tun, als müsste ich alles allein schaffen': 'audio/pro/pro_277.mp3',
  'möchtest du, dass ich bei dir bleibe': 'audio/pro/pro_278.mp3',
  'dein freund möchte lieber kurz allein sein. was machst du': 'audio/pro/pro_279.mp3',
  'auch ein trauriges kind darf nein sagen. du kannst später hilfe anbieten': 'audio/pro/pro_280.mp3',
  'seinen wunsch achten und später wieder fragen': 'audio/pro/pro_281.mp3',
  'dich trotzdem ganz dicht daneben setzen': 'audio/pro/pro_282.mp3',
  'ich bin wütend. ich brauche eine pause': 'audio/pro/pro_283.mp3',
  'die wut ist noch da. was kannst du tun': 'audio/pro/pro_284.mp3',
  'gefühle müssen nicht sofort weggehen. deine hände bleiben sicher und du darfst hilfe holen': 'audio/pro/pro_285.mp3',
  'abstand halten und eine vertraute person um hilfe bitten': 'audio/pro/pro_286.mp3',
  'jemanden hauen, damit die wut weggeht': 'audio/pro/pro_287.mp3',
  'in dieser gruppe folgt auf gelber kreis: blauer kreis. dann wiederholt sich die gruppe': 'audio/pro/pro_288.mp3',
  'in dieser gruppe folgt auf blauer kreis: gelber kreis. dann wiederholt sich die gruppe': 'audio/pro/pro_289.mp3',
  'in dieser gruppe folgt auf herz: stern. dann wiederholt sich die gruppe': 'audio/pro/pro_290.mp3',
  'in dieser gruppe folgt auf stern: herz. dann wiederholt sich die gruppe': 'audio/pro/pro_291.mp3',
  'in dieser gruppe folgt auf baum: blume. dann wiederholt sich die gruppe': 'audio/pro/pro_292.mp3',
  'in dieser gruppe folgt auf blume: baum. dann wiederholt sich die gruppe': 'audio/pro/pro_293.mp3',
  'in dieser gruppe folgt auf gelber kreis: lila kreis. dann wiederholt sich die gruppe': 'audio/pro/pro_294.mp3',
  'in dieser gruppe folgt auf lila kreis: grüner kreis. dann wiederholt sich die gruppe': 'audio/pro/pro_295.mp3',
  'in dieser gruppe folgt auf grüner kreis: gelber kreis. dann wiederholt sich die gruppe': 'audio/pro/pro_296.mp3',
  'in dieser gruppe folgt auf stern: teddybär. dann wiederholt sich die gruppe': 'audio/pro/pro_297.mp3',
  'in dieser gruppe folgt auf teddybär: buch. dann wiederholt sich die gruppe': 'audio/pro/pro_298.mp3',
  'in dieser gruppe folgt auf buch: stern. dann wiederholt sich die gruppe': 'audio/pro/pro_299.mp3',
  'in dieser gruppe folgt auf regenbogen: mond. dann wiederholt sich die gruppe': 'audio/pro/pro_300.mp3',
  'in dieser gruppe folgt auf mond: sonne. dann wiederholt sich die gruppe': 'audio/pro/pro_301.mp3',
  'in dieser gruppe folgt auf sonne: regenbogen. dann wiederholt sich die gruppe': 'audio/pro/pro_302.mp3',
};
